### ISSUE TITLE
[BUG] Problem between resize-observer-polyfill and @types/resize-observer-browser

### ISSUE THREAD

**Issue by BenLune** [ng-web-apis/resize-observer#13]
Hi,
Thank you and congrats for this lib ! I wanted to let you know that I noticed that there is a potential conflict between resize-observer-polyfill and @types/resize-observer-browser. The polyfill project seems to have its own types now, and when you had it to a project with ng-web-apis/resize-observer as dependency, we have a conflict error on compilation due to conflicts between resize-observer-polyfill and @types/resize-observer-browser types definition I guess.
Unfortunately, I had to remove this lib from my project, and manage it myself. I'd be glad to give it another when you'll have time to solve this problem.

'Hope my feedback helps :-)

Cheers,
Benoît

**Comment by waterplea** [comment]
Hi @BenLune 
Thank you for your interest in our library. I'm sorry it's not working out for you, but that's an issue with the polyfill. You might try opening an issue there. Until ResizeObserver types are introduced to TypeScript, @types package is the defacto official source of types so that polyfill should probably switch to using those.

**Comment by Dylan0405** [comment]
@BenLune 
I meet the same bug too. Could you tell me how did  you manage it ?

**Comment by waterplea** [comment]
I noticed latest version of TypeScript has types built-in and also latest version of @types/resize-observer-browser (0.1.15) is comptible with them. So you might try bumping the version and reinstalling it.

**Comment by Dylan0405** [comment]
@waterplea 
Thank you for your advice.But it may not works for me , in my project, Angular 11 is not support  the latest version of TypeScript. And for now there is no plan to update to 12.
