### ISSUE TITLE
[BUG] ResizeObserver types conflict 

### ISSUE THREAD

**Issue by KIAIgorMD** [ng-web-apis/resize-observer#15]
# 🐞 Bug report

### Description

type conflict due to duplication

<img width="1640" alt="Screenshot 2021-05-13 at 11 41 35" src="https://user-images.githubusercontent.com/8413395/118104641-0ef84880-b3e4-11eb-8269-7838f409ac53.png">

### Reproduction

Create empty angular app with this package and start app

### Versions

-   OS: -
-   Browser -
-   Angular 12

**Comment by waterplea** [comment]
It appears that latest version of @types/resize-observer-browser is compatible with modern TypeScript so we will bump it in Taiga UI to work with old Angular versions and in TypeScript 4.2+ no additional types are required.
