### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by catflinger** [ng-web-apis/resize-observer#16]
# 🚀 Feature request

### Is your feature request related to a problem?

Following the install/usage instructions for Resize Observable does not provide a working example. 

The step to import `ResizeObserverModule` in `module.ts` is missing.

I wasted quite a bit of time wondering why nothing worked until I realised this. 

And also, while you are in there ;) 

`npm install --save @types/resize-observer-browser`

would be better as `--save-dev`

### Describe the solution you'd like

Update the install/usage instructions to mention the need to add `ResizeObserverModule` to `imports`

### Describe alternatives you've considered

None.

**Comment by waterplea** [comment]
Thank you for highlighting this! Updated `README`
